spring:
    datasource:
            generate-unique-name: false
            name : tacocloud
    
    data: 
        rest:
            base-path: /data-api
            

logging:
        level:
            org:
                springframework:
                    security:
                        web:
                            FilterChainProxy: DEBUG

            
